# Generated by Django 3.1.7 on 2021-04-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210403_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometheater',
            name='img1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='hometheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='hometheater',
            name='img2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='hometheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='hometheater',
            name='img3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='hometheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='hometheater',
            name='img4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='hometheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='hometheater',
            name='img5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='hometheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='hometheater',
            name='img6',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='hometheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='hometheater',
            name='img7',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='hometheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixer',
            name='feature',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='juicermixer',
            name='img1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicerproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixer',
            name='img2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicerproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixer',
            name='img3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicerproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixer',
            name='img4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicerproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixer',
            name='img5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicerproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixer',
            name='img6',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicerproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixer',
            name='img7',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicerproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixergrinder',
            name='features',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='juicermixergrinder',
            name='img1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicergrinderproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixergrinder',
            name='img2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicergrinderproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixergrinder',
            name='img3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicergrinderproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixergrinder',
            name='img4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicergrinderproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixergrinder',
            name='img5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicergrinderproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixergrinder',
            name='img6',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicergrinderproductimages/'),
        ),
        migrations.AlterField(
            model_name='juicermixergrinder',
            name='img7',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='juicergrinderproductimages/'),
        ),
        migrations.AlterField(
            model_name='towertheater',
            name='feature',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='towertheater',
            name='img1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='towertheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='towertheater',
            name='img2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='towertheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='towertheater',
            name='img3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='towertheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='towertheater',
            name='img4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='towertheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='towertheater',
            name='img5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='towertheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='towertheater',
            name='img6',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='towertheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='towertheater',
            name='img7',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='towertheaterproductimages/'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='additionalFeatures',
            field=models.CharField(max_length=200),
        ),
    ]
