# Generated by Django 3.1.7 on 2021-04-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productid',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
