# Generated by Django 3.1.7 on 2021-04-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_cart_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
    ]
