# Generated by Django 3.1.7 on 2021-04-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_cart_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
