# Generated by Django 3.1.7 on 2021-04-10 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20210406_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airCooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.aircooler')),
                ('attaChakki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.attachakki')),
                ('homeTheater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.hometheater')),
                ('hotplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.hotplate')),
                ('iron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.iron')),
                ('juicerMixer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.juicermixer')),
                ('juicerMixerGrinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.juicermixergrinder')),
                ('refrigerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.refrigerator')),
                ('towerTheater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.towertheater')),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.tv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
            ],
        ),
    ]
