# Generated by Django 3.1.7 on 2021-04-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='airCooler',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.aircooler'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='attaChakki',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.attachakki'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='homeTheater',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.hometheater'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='hotplate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.hotplate'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='iron',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.iron'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='juicerMixer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.juicermixer'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='juicerMixerGrinder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.juicermixergrinder'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='refrigerator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.refrigerator'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='towerTheater',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.towertheater'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='tv',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.tv'),
        ),
    ]
